artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  command: kaggle datasets download -d xiataokang/tinyimagenettorch
  local_data_file: artifacts/data_ingestion/tinyimagenettorch.zip
  unzip_dir: artifacts/data_ingestion

data_cleaning:
  remove_folder_dir: artifacts/data_ingestion/tiny-imagenet-200/test
  remove_train_file_dir: artifacts/data_ingestion/tiny-imagenet-200/train
  remove_file_extention: txt
  remove_zip_dir: artifacts/data_ingestion/tinyimagenettorch.zip

feature_representation:
  root_dir: artifacts/embeddings
  data_path: artifacts/data_ingestion/tiny-imagenet-200/train
  feature_dir: artifacts/embeddings/embedding.pkl
  image_path_list_dir: artifacts/embeddings/path_list.pkl
  image_labels: artifacts/embeddings/labels.pkl

model_trainer:
  root_dir: artifacts/model
  feature_dir: artifacts/embeddings/embedding.pkl
  image_path_list_dir: artifacts/embeddings/path_list.pkl
  model_path: artifacts/model/image_search_engine_classifier.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model/image_search_engine_classifier.pkl
  image_labels_path: artifacts/embeddings/labels.pkl
  image_path_list_dir: artifacts/embeddings/path_list.pkl
  val_path: artifacts/data_ingestion/tiny-imagenet-200/val
  val_feature: artifacts/embeddings/val_embedding.pkl

prediction:
  root_dir: artifacts/predictions
  model_path: artifacts/model/image_search_engine_classifier.pkl
  image_path_list_dir: artifacts/embeddings/path_list.pkl
